# Generated by Django 5.0.6 on 2024-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'INCOME'), (2, 'EXPENSE')], default=1),
        ),
    ]
